opendatahub-io/elyra

.gitignore
README.md

Set context that this fork is for opendatahub usecase only

Set context that this fork is for opendatahub usecase only

---

elyra/metadata/schemas/kfp.json
elyra/pipeline/kfp/kfp_authentication.py
elyra/pipeline/kfp/processor_kfp.py

Set the changes required for the ODH environments

Set the changes required for the ODH environments

---

pyproject.toml

Cap kfp version for avoiding protobuf version dependency

Cap kfp version for avoiding protobuf version dependency

---

elyra/templates/kubeflow/v2/python_dsl_template.jinja2

The PR updates methods used in the jinja template for the object PipelineTask in compliance with kfp v2.
Related-to: https://issues.redhat.com/browse/RHOAIENG-4699
Building Elyra with the proposed changes in local and submitting pipeline to a v2 pipeline server succeeds as expected.
by me, under the same open source license …

fix: update container properties according to kfpv2

---

elyra/templates/kubeflow/v2/python_dsl_template.jinja2
pyproject.toml

Sync the changes from kfpv2 branch to release.

Sync the changes from kfpv2 branch to release.

---

elyra/templates/kubeflow/v2/python_dsl_template.jinja2

[dspv2] sync dspv2 branch with kfpv2

[dspv2] sync dspv2 branch with kfpv2

---

elyra/templates/kubeflow/v2/python_dsl_template.jinja2

Import add toleration method imported from `kfp-kubernetes`.
Run a pipeline by adding tolerations.
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some other
person who certified (a), (b) …

fix: Adjust with the  updated kfp-kubernetes functions

---

cypress.json
package.json
tests/integration/01-scriptdebugger.ts
tests/integration/codesnippet.ts
tests/integration/codesnippetfromselectedcells.ts
tests/integration/pipeline.ts
tests/integration/pythoneditor.ts
tests/integration/submitnotebookbutton.ts
tests/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap
tests/snapshots/pipeline-editor-tests/matches-empty-pipeline-snapshot.1.snap
tests/snapshots/pipeline-editor-tests/matches-simple-pipeline-snapshot.1.snap
tests/support/commands.ts
tests/tsconfig.json
tests/utils/snapshots/plugin.ts
yarn.lock

After this PR, we are supposed to have a stable CI with 41 out of 60 integration tests passing.
The 19 tests that are failing are being skipped:
- 15 of them depend on https://issues.redhat.com/browse/RHOAIENG-12695
- 4 of them are flaky. https://issues.redhat.com/browse/RHOAIENG-12778
If you see an integration test failing, please try to rerun the CI.
If the error persists, please let me know.
I'm also disabling the Cypress video recording feature as it makes the tests more stable on the CI.
We can enable it locally or temporarily on a PR if necessary.

Fix some integration tests and disable those that are failing

---

elyra/metadata/schemas/airflow.json
elyra/metadata/schemas/code-snippet.json
elyra/metadata/schemas/kfp.json
elyra/metadata/schemas/metadata-test.json
elyra/metadata/schemas/metadata-test2.json
elyra/metadata/schemas/runtime-image.json
elyra/metadata/schemas/url-catalog.json
elyra/pipeline/airflow/package_catalog_connector/airflow-package-catalog.json
elyra/pipeline/airflow/provider_package_catalog_connector/airflow-provider-package-catalog.json
packages/code-snippet/src/CodeSnippetWidget.tsx
packages/metadata/src/index.ts
packages/ui-components/package.json
packages/ui-components/src/FormComponents/CodeBlock.tsx
packages/ui-components/src/FormComponents/Tags.tsx
packages/ui-components/src/FormEditor.tsx
tests/integration/codesnippet.ts
tests/integration/codesnippetfromselectedcells.ts
tests/integration/pipeline.ts
yarn.lock

https://issues.redhat.com/browse/RHOAIENG-12695
Follow up tasks:
- https://issues.redhat.com/browse/RHOAIENG-12849
- https://issues.redhat.com/browse/RHOAIENG-12850
- https://issues.redhat.com/browse/RHOAIENG-12851

RHOAIENG-12695: Migrate custom form renderers from metadata package to JL 4.x plus fixes

---

packages/script-editor/src/ScriptRunner.ts

https://issues.redhat.com/browse/RHOAIENG-12697
https://github.com/user-attachments/assets/34c08acd-76fd-4a6b-855b-0edf596dc77f
**Note**: As stated in Elyra's [docs](https://elyra.readthedocs.io/en/latest/user_guide/enhanced-script-support.html#python-script-debugging-support-experimental), the debug support is an experimental feature with some known issues (see [here](https://github.com/elyra-ai/elyra/pull/2087) and [here](https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aopen+is%3Aissue+label%3Apkg%3Adebugger)).

RHOAIENG-12697: Fix Run/Debug on Python editor extension

---

packages/pipeline-editor/src/PipelineEditorWidget.tsx
packages/ui-components/src/BrowseFileDialog.tsx
tests/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap

RHOAIENG-13979: Filename can't be edited on node properties
RHOAIENG-13981: File dependencies browsing does not select file

Fix pipeline editor path handling

---

packages/pipeline-editor/src/PipelineEditorWidget.tsx
packages/ui-components/src/BrowseFileDialog.tsx
tests/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap

RHOAIENG-13979: Filename can't be edited on node properties
RHOAIENG-13981: File dependencies browsing does not select file

Fix pipeline editor path handling (#54)

---

packages/pipeline-editor/src/PipelineEditorWidget.tsx

https://issues.redhat.com/browse/RHOAIENG-13982
https://github.com/user-attachments/assets/0e13e921-8789-440b-8643-39f49a15e84a

RHOAIENG-13982: Filter out `undefined` values on pipeline change

---

packages/pipeline-editor/src/PipelineEditorWidget.tsx
packages/pipeline-editor/src/index.ts

[https://issues.redhat.com/browse/RHOAIENG-13688](https://issues.redhat.com/browse/RHOAIENG-13688)
[rename.webm](https://github.com/user-attachments/assets/1e85f0a6-b440-429f-9750-f687a34fae10)

RHOAIENG-13688: Infinite loading after renaming a new txt file to pipeline extension

---

packages/code-snippet/src/index.ts
packages/metadata-common/src/MetadataWidget.tsx
packages/metadata/src/index.ts
packages/pipeline-editor/src/index.ts

[https://issues.redhat.com/browse/RHOAIENG-12696](https://issues.redhat.com/browse/RHOAIENG-12696)
[code_snippet.webm](https://github.com/user-attachments/assets/fad5490b-0e31-4fc2-b360-7e596114dd5e)

RHOAIENG-12696: Fix Code Snippet editor header text

---

.github/workflows/scripts/update_version.sh

Validation: https://github.com/caponetto/opendatahub-io-elyra/pull/10

Update the root `package.json` too on the automated script to update version

---

.github/workflows/scripts/update_version.sh

Cherry-picking https://github.com/opendatahub-io/elyra/pull/71 to v4.1.x just in case we need a new release from this branch.

[`4.1.x`] Update the root package.json on the automated script

---

packages/pipeline-editor/src/PipelineEditorWidget.tsx
packages/pipeline-editor/src/pipeline-hooks.ts
tests/integration/pipeline.ts
tests/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap
tests/snapshots/pipeline-editor-tests/matches-simple-pipeline-snapshot.1.snap

See https://issues.redhat.com/browse/RHOAIENG-16309 for more details
Notebook-based images to use for tests (commit e64e150800c0b3b46a6aa8f362be9acf15ce28ba):
```
ghcr.io/caponetto/opendatahub-io-elyra/workbench-images:jupyter-trustyai-ubi9-python-3.11-20241203-3f95611-sha-f1efbfb5
ghcr.io/caponetto/opendatahub-io-elyra/workbench-images:cuda-jupyter-tensorflow-ubi9-python-3.11-20241203-3f95611-sha-f1efbfb5
```
Demo running on the image above:
https://github.com/user-attachments/assets/0976287e-0d45-46a3-9456-8ae26f109991

RHOAIENG-16309: Fix some properties not being added in the Pipeline Properties tab

---

.github/workflows/build.yml
Makefile
pyproject.toml
test_requirements.txt

https://issues.redhat.com/browse/RHOAIENG-15235
Upload coverage reports from `jest` & `pytest` to Codecov

RHOAIENG-15235: Add test coverage support

---

.github/workflows/build.yml
.gitignore
.nycrc
Makefile
package.json
packages/code-snippet/package.json
packages/metadata-common/package.json
packages/metadata/package.json
packages/pipeline-editor/package.json
packages/pipeline-editor/src/PipelineEditorWidget.tsx
packages/pipeline-editor/src/RuntimesWidget.tsx
packages/pipeline-editor/src/test/pipeline-hooks.spec.ts
packages/python-editor/package.json
packages/script-debugger/package.json
packages/script-debugger/src/index.ts
packages/script-editor/package.json
packages/services/package.json
packages/theme/package.json
packages/ui-components/package.json
packages/ui-components/src/FormComponents/Tags.tsx
tests/plugins/index.ts
tests/support/commands.ts
tests/support/index.d.ts
tests/tsconfig.json
testutils/jest.config.js
testutils/tsconfig.jest.json
tsconfig.base.json
yarn.lock

FUP of https://github.com/opendatahub-io/elyra/pull/89

Report coverage from cypress tests

---

.github/workflows/build.yml
Makefile
cypress/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap
cypress/tests/pipeline.cy.ts
etc/config/metadata/runtime-images/anaconda-py311.json
etc/config/metadata/runtime-images/anaconda-py312.json
etc/config/metadata/runtime-images/anaconda.json
etc/config/metadata/runtime-images/pandas.json
etc/config/metadata/runtime-images/pytorch-devel.json
etc/config/metadata/runtime-images/pytorch-runtime.json
etc/config/metadata/runtime-images/r.json
etc/config/metadata/runtime-images/tensorflow_2x_gpu_py3.json
etc/config/metadata/runtime-images/tensorflow_2x_py3.json

FUP of https://github.com/opendatahub-io/elyra/pull/94. 
Cherry-pick from upstream:
- https://github.com/elyra-ai/elyra/pull/3255
- https://github.com/elyra-ai/elyra/pull/3257

Go back using `ubuntu-latest` on `validate-images` job

---

.github/workflows/codeql-analysis.yml
elyra/airflow/bootstrapper.py
elyra/kfp/bootstrapper.py

Cherry-pick commits from upstream:
- https://github.com/elyra-ai/elyra/pull/3300
- https://github.com/elyra-ai/elyra/pull/3304

Fix GitHub workflows

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/update-version-through-pr.yml
Makefile
elyra/airflow/bootstrapper.py
elyra/kfp/bootstrapper.py
etc/templates/setup.py
pyproject.toml

https://issues.redhat.com/browse/RHOAIENG-25809
Cherry-pick from upstream: https://github.com/elyra-ai/elyra/pull/3311

Add support to Python `3.12` and `3.13`
