opendatahub-io/elyra

- elyra/cli/pipeline_app.py
- elyra/pipeline/pipeline_definition.py
fix: rebuild subclass map with runtime class
commit picked from: https://github.com/elyra-ai/elyra/pull/3195
> fix: rebuild subclass map with runtime class

- elyra/templates/kubeflow/v2/python_dsl_template.jinja2
This PR removes the helper function that sets the image pull policy for a task.
The error was caused due to `image_policy` not being defined in `kubernetes_executor_config_pb2` in the latest release.
> fix: remove helper method to set image pull policy

- elyra/templates/kubeflow/v2/python_dsl_template.jinja2
This PR removes the helper functions for methods that are missing in the latest release.
The elyra runs were running into issues as the generated file `/kubernetes_executor_config_pb2.py` does not yet support this methods.
> fix: remove helper methods for adding toleration

- elyra/pipeline/kfp/processor_kfp.py
Use fallback url for `bootstrapper.py` if an invalid URL is provided.
> fix: use fallback url if the provided url is invalid

- elyra/metadata/schemas/kfp.json
- elyra/pipeline/processor.py
1. Modify logic so that API endpoint shoiuld have the URL scheme as an optional.
1. Run `elyra-metadata list runtimes`.
2. Modify the api endpoint.
3. You should see that Elyra UI's runtime section loads the runtime without issue.
Fixes [RHOAIENG-5071](https://issues.redhat.com/browse/RHOAIENG-5071)
by me, under the same …
> fix: allow kubeflow api endpoint to have scheme as optional

- elyra/pipeline/kfp/processor_kfp.py
Set the run_url with experiment info included
The run_url is set in the format of: `{experiment_id}/runs/{run_id}`
Example:
```
https://rhods-dashboard-redhat-ods-applications.apps.datahub.redhat.com/experiments/experiment/024e260b-75e9-407e-9e8d-3974320c06dc/runs/b6c920a2-a3de-452c-bf58-88d46f3da65b
```
Related-to: https://issues.redhat.com/browse/RHOAIENG-8398
> Set the run_url with experiment info included

- elyra/kfp/bootstrapper.py
consolidate logs of Python script into container logs
Run the pipeline with below script:
>python script
```
a = 10
b = 0
c = a/b
```
> consolidate logs of python script into container logs

- Makefile
See PR title.
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.
(d) I understand and agree that this project and …
> Add `--force-reinstall` to `install-server-package` target

- elyra/pipeline/kfp/processor_kfp.py
- elyra/tests/pipeline/kfp/test_processor_kfp.py
- elyra/tests/pipeline/resources/components/filter_text.yaml
`test_generate_pipeline_dsl_compile_pipeline_dsl_custom_component_pipeline`
Remove Tekton part
`test_generate_pipeline_dsl_compile_pipeline_dsl_custom_components_with_parameters`
Adapt the YAML component and remove redundant checks
For both tests to pass, we also need a small change on `processor_kfp.py`. 
In KFP DSL v1, the inputs of a `Component` object are placed in a list but now it is a dictionary.
This is probably causing issues at runtime. 🤔
> Fix 2 tests

- elyra/tests/cli/test_pipeline_app.py
Applies to:
- `test_export_kubeflow_output_option`
- `test_export_kubeflow_overwrite_option`
- `test_export_kubeflow_format_option`
> Improve reason to skip tests

- elyra/tests/pipeline/kfp/test_processor_kfp.py
Just an updated analysis on a test failure. The test will continue to be skipped, due to a regression on the KFP v1 to v2 migration.  
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some …
> RHOAIENG-11956 : Adding some information on test failure

- packages/ui-components/src/FormComponents/CodeBlock.tsx
- tests/integration/codesnippet.ts
- tests/integration/codesnippetfromselectedcells.ts
https://issues.redhat.com/browse/RHOAIENG-12851
Setting CodeBlock editor source through `setSource` instead of `sharedModel` just like in `CodeSnippetWidget`. 
With this change, we've got back 3 integration tests that were disabled.
> RHOAIENG-12851: Fix blank tab when trying to edit a code snippet

- .github/workflows/release.yml
In order to publish the elyra packages to pypi, push a tag with the format `v<version>` to the repository.
Fixes: https://issues.redhat.com/browse/RHOAIENG-11709
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was …
> RHOAIENG-11709: Adding a release github action 

- packages/code-snippet/package.json
- packages/code-snippet/src/CodeSnippetWidget.tsx
- tests/integration/codesnippet.ts
- yarn.lock
https://issues.redhat.com/browse/RHOAIENG-12850
Use `EditorLanguageRegistry` to resolve the editor language based on the model's mimeType. The previous approach is not applicable anymore. With this fix, one integration test is back alive.
> RHOAIENG-12850: Fix no warning is shown if a code snippet is added to a file with different language

- packages/ui-components/src/FormComponents/Tags.tsx
https://issues.redhat.com/browse/RHOAIENG-12849
**Before**
**After**
https://github.com/user-attachments/assets/58aa3628-ca84-4bc7-a7db-7c28b180c86a
> RHOAIENG-12849: Fix `Tags` component style

- packages/metadata-common/src/FilterTools.tsx
https://issues.redhat.com/browse/RHOAIENG-13167
Apply the same fix done in https://github.com/opendatahub-io/elyra/pull/41 since the code is duplicated.
Before
After
> RHOAIENG-13167: Fix Tags component style used by the Filter tools

- docs/source/recipes/running-elyra-in-air-gapped-environment.md
- elyra/pipeline/kfp/processor_kfp.py
set ELYRA_FILE_BASE_PATH var for using the script embedded in runtime images
Related-to: https://issues.redhat.com/browse/RHOAIENG-13044
Tested with notebook image: `quay.io/harshad16/datascience:patch1`
As the elyra component in workbench, isn't aware if the files are embedded in runtime images, 
thus, we expanded the command, to first verify, if the files already present, if yes, use them or else download from URL.
Notes: once this PR is merged and elyra is released.
https://github.com/opendatahub-io/notebooks/blob/main/jupyter/datascience/ubi9-python-3.11/setup-elyra.sh#L21-L24
These bits needs to be removed from workbenches for this to take effect fully.
> RHOAIENG-13044: set ELYRA_FILE_BASE_PATH var for script embedded in runtime images

- elyra/pipeline/kfp/processor_kfp.py
- etc/generic/requirements-elyra.txt
Upgrade requirement package with most compatible
Related-to: https://issues.redhat.com/browse/RHOAIENG-13044
- Cherry-picked upstream fixes: https://github.com/elyra-ai/elyra/pull/3240
This issue occurs on jupyterlab4 branch as well.
- change default elyra_github_branch to be pointed at jupyterlab4, till we do dev releases.
> Upgrade requirement package with most compatible

- .github/workflows/build.yml
- .github/workflows/release.yml
- Makefile
- docs/source/developer_guide/development-workflow.md
- etc/docker/kubeflow/README.md
Targets in the Makefile that touch the UI building process now have `prod` and `dev` versions.
> Allow production builds for UI packages

- .github/workflows/build.yml
- .github/workflows/release.yml
- Makefile
- docs/source/developer_guide/development-workflow.md
- etc/docker/kubeflow/README.md
Cherry-pick from https://github.com/opendatahub-io/elyra/pull/50
> [`v4.0.x`] Allow production builds for UI packages

- elyra/_version.py
- lerna.json
- package.json
- packages/code-snippet/package.json
- packages/metadata-common/package.json
- packages/metadata/package.json
- packages/pipeline-editor/package.json
- packages/python-editor/package.json
- packages/script-debugger/package.json
- packages/script-editor/package.json
- packages/services/package.json
- packages/theme/package.json
- packages/ui-components/package.json
- yarn.lock
- The `main` branch keeps growing forever with new code
- Every time a release is needed (even a test one), we branch out `main` and adjust the version accordingly
- If applicable, additional fixes done on the release branches must be cherry-picked to `main` branch
- A release branch is never merged back to `main` branch
> Use static `0.0.0` version on `main`

- docs/requirements.txt
The `Test Documentation Build` job started to fail on the weekend because `sphinx_rtd_theme` [released](https://github.com/readthedocs/sphinx_rtd_theme/tags) a new version that has deprecated things. Let's freeze the version that we were currently using to bring back the failing job to green.
> Use version `2.0.0` for `sphinx_rtd_theme`

- packages/pipeline-editor/src/index.ts
- packages/python-editor/src/index.ts
- tests/integration/pipeline.ts
- tests/integration/pythoneditor.ts
https://issues.redhat.com/browse/RHOAIENG-12830
Add entries for Pipeline and Python editors.
Result:
https://github.com/user-attachments/assets/ac1bf984-f509-4861-8577-139dddf5f6ec
I've added separators so that it looks similar to the "File -> New" menu:
> RHOAIENG-12830: Add Elyra shortcuts to file explorer context menu

- packages/pipeline-editor/src/PipelineEditorWidget.tsx
https://issues.redhat.com/browse/RHOAIENG-13010
Note: It has the behavior of listing the files from the parent folder, just like browsing the input or file dependencies. We should probably review this behavior.
https://github.com/user-attachments/assets/9f3eddb9-336f-473d-b9a6-45a31b776a2d
> RHOAIENG-13010: Fix create new node from context menu

- .github/workflows/scripts/update_version.sh
- .github/workflows/update-version-through-pr.yml
- lerna.json
https://issues.redhat.com/browse/RHOAIENG-13909
Validation:
- From `main` to a release branch (`0.0.0` -> `4.1.0`): https://github.com/caponetto/opendatahub-io-elyra/pull/6
- From `v4.0.x` to itself (`4.0.3` -> `4.2.0`): https://github.com/caponetto/opendatahub-io-elyra/pull/8
**NOTE**: The source branch must have these scripts included, otherwise the workflow will fail.
> RHOAIENG-13909: Script and workflow to bump Elyra's version

- packages/script-editor/src/KernelDropdown.tsx
- packages/script-editor/style/index.css
https://issues.redhat.com/browse/RHOAIENG-13877
Use the `HTMLSelect` component from `@jupyterlab/ui-components` just like the Python Notebook does.
https://github.com/user-attachments/assets/b48d1aa1-deec-4e07-a7f1-80957b1ed63c
> RHOAIENG-13877: Fix kernel dropdown style for Dark theme

- packages/pipeline-editor/src/PipelineEditorWidget.tsx
https://issues.redhat.com/browse/RHOAIENG-12831
**Current Behavior** | **New Behavior**
--- | ---
| - List only files, not folders <br>- Cannot navigate between folders<br> - List files in the root folder if the pipeline file is in the root folder<br>- List files in the parent folder of the folder where the pipeline file is |- List files and folders<br> - Can navigate between folders<br> - List files in the folder where the pipeline file is |
**Current Behavior** | **New Behavior**
--- | ---
| - List only files, not folders<br>- Cannot navigate between folders<br>- When there is a value for the input path, it lists the folder where the given input file path is<br>- When the value is empty, it lists files in the root if the pipeline file is in the root. Otherwise, it lists files in the …
> RHOAIENG-12831: Standardize file selection on pipeline editor

- .github/workflows/build.yml
- .github/workflows/purge-ghcr.yaml
- .github/workflows/scripts/free_gha_space.sh
https://issues.redhat.com/browse/RHOAIENG-13039
In this PR:
- Script to free up disk space ([reference](https://github.com/opendatahub-io/notebooks/blob/v1.24.0/.github/workflows/build-notebooks-TEMPLATE.yaml#L39))
- Workflow to purge images older than 3 weeks ([reference](https://github.com/opendatahub-io/notebooks/blob/v1.24.0/.github/workflows/purge-ghcr.yaml))
- Enhancement to `Elyra CI` to build notebook-based images with the current Elyra code
Notes:
- We can add as many images as we want to `QUAY_WORKBENCH_IMAGES_TAG_PREFIX_CSV`. I chose to start with the TrustyAI and CUDA-TF images because the first one is light enough to be run by anyone locally. The second one enables us to execute the tutorials from the sanity checks if the image is running on ODH.
- The more images we add to …
> RHOAIENG-13039: Build notebook-based images with the current Elyra code

- .github/workflows/build.yml
As the newest tag comes first, use `filter_tag_name=like:<tag_prefix>` and `limit=1` instead of fetching/sorting all the tags and picking the first one, which is paginated and could lead to issues.
Validation: https://github.com/caponetto/opendatahub-io-elyra/actions/runs/11665431548/job/32478187063
> ci: Improve tag resolution on the Build notebook images step

- Makefile
- pyproject.toml
In this PR:
- As the CI started to throw `EnvironmentLocationNotFound`, add a check to run `conda env remove` only if the env exists.
- Cap `kfp` to the exact version we've been using for a while (`==2.9.0`). The new `v2.10.0` release brings breaking changes so it can be updated in a separate PR.
> Fix new failures on CI

- elyra/_version.py
- lerna.json
- package.json
- packages/code-snippet/package.json
- packages/metadata-common/package.json
- packages/metadata/package.json
- packages/pipeline-editor/package.json
- packages/python-editor/package.json
- packages/script-debugger/package.json
- packages/script-editor/package.json
- packages/services/package.json
- packages/theme/package.json
- packages/ui-components/package.json
- yarn.lock
This way, we are compatible with the [original code](https://github.com/opendatahub-io/elyra/blob/main/elyra/pipeline/kfp/processor_kfp.py#L1065) and we don't need to set up one additional env var when testing versions from `main`.
> Append 'dev' suffix to the version on main branch

- packages/metadata-common/src/MetadataEditor.tsx
- packages/ui-components/src/FormEditor.tsx
- tests/integration/codesnippet.ts
https://issues.redhat.com/browse/RHOAIENG-15041
Notebook-based images to use for tests (commit 3679179af4af9842f066761a3f964462d0d5ddcc):
```
ghcr.io/caponetto/opendatahub-io-elyra/workbench-images:jupyter-trustyai-ubi9-python-3.11-20241203-3f95611-sha-3679179a
ghcr.io/caponetto/opendatahub-io-elyra/workbench-images:cuda-jupyter-tensorflow-ubi9-python-3.11-20241203-3f95611-sha-3679179a
```
Demo running on the image above:
https://github.com/user-attachments/assets/26aa41d2-633b-48d8-97d1-2c880f31301d
> RHOAIENG-15041: Show validation warnings only after the first form submission

- Makefile
While setting up a new development environment from scratch, I noticed that the target `build-dependencies` wasn't being included as part of the dev build.
> Add missing make target to dev builds

- .github/workflows/build.yml
A permanent solution that works on `ubuntu-latest` (`24.04`) will be investigated.
> Pin Ubuntu `22.04` on `validate-images` job to unblock the CI

- pyproject.toml
- test_requirements.txt
Fixes `Test Server` jobs that failed on https://github.com/opendatahub-io/elyra/actions/runs/12545186590
> Pin `nbconvert` to fix a test issue

- pyproject.toml
- test_requirements.txt
Rollback https://github.com/opendatahub-io/elyra/pull/96 since https://github.com/jupyter/nbconvert/issues/2198 is resolved and released.
> Unpin `nbconvert` since the issue with `mistune` is resolved

- .eslintrc.json
- cypress/tests/reditor.cy.ts
- labextensions/elyra_code_viewer_extension/__init__.py
- labextensions/elyra_r_editor_extension/__init__.py
- labextensions/elyra_scala_editor_extension/__init__.py
- packages/code-viewer/install.json
- packages/code-viewer/package.json
- packages/code-viewer/setup.py
- packages/code-viewer/src/CodeViewerWidget.ts
- packages/code-viewer/src/index.ts
- packages/code-viewer/style/index.css
- packages/code-viewer/tsconfig.json
- packages/r-editor/install.json
- packages/r-editor/package.json
- packages/r-editor/setup.py
- packages/r-editor/src/REditor.tsx
- packages/r-editor/src/index.ts
- packages/r-editor/style/index.css
- packages/r-editor/tsconfig.json
- packages/scala-editor/install.json
- packages/scala-editor/package.json
- packages/scala-editor/setup.py
- packages/scala-editor/src/ScalaEditor.tsx
- packages/scala-editor/src/index.ts
- packages/scala-editor/style/index.css
- packages/scala-editor/tsconfig.json
- pyproject.toml
- yarn.lock
These extensions got entirely removed on https://github.com/opendatahub-io/elyra/pull/4 because they are not required on ODH environment. However, it generates conflicts when syncing upstream with this fork. To mitigate potential unwanted conflicts, this PR readds these deleted extensions from upstream, which are now part of the build flow but are still not included in ODH distribution.
> Readd deleted extensions (Code Viewer, Scala and R editors)

- elyra/pipeline/kfp/processor_kfp.py
- elyra/templates/kubeflow/v2/python_dsl_template.jinja2
- elyra/tests/pipeline/kfp/conftest.py
- elyra/tests/pipeline/kfp/test_processor_kfp.py
Here's a container image for validation that includes these changes: 
```
ghcr.io/caponetto/opendatahub-io-elyra/workbench-images:cuda-jupyter-tensorflow-ubi9-python-3.11-20250310-bc34348-sha-d37b477d
```
Need to add the following env var to the running pod:
```
KF_PIPELINES_SSL_SA_CERTS=/etc/pki/tls/custom-certs/ca-bundle.crt
```
> Fix disable cache mechanism

- pyproject.toml
Although the JupyterLab version that we have been extensively testing is `4.2.x` in our images (see [here](https://github.com/opendatahub-io/notebooks/blob/main/jupyter/minimal/ubi9-python-3.11/Pipfile#L11)), this PR increases the compatibility with JupyterLab up to the version `4.4`, which allows us to start validating the new versions.
> Update JupyterLab version compatibility

- package.json
The `packageManager` prop was unintentionally added by the update-version workflow and will be introduced only when we cherry-pick https://github.com/elyra-ai/elyra/pull/3292 from upstream.
> Remove unneeded `packageManager` from `package.json` to fix the CI
